export const RESERVED_SLUGS = [
  "admin",
  "dashboard",
  "auth",
  "api",
  "config",
  "login",
  "entrar",
  "cadastro",
  "onboarding",
  "test",
  "suporte",
  "ajuda",
  "help",
  "settings",
  "configuracoes",
  "perfil",
  "profile",
  "slug",
  "vendedor",
  "vendedores",
  "catalogos",
  "produtos",
  "analytics",
  "bi",
  "global",
  "root",
  "sys",
  "system",
  "sistema",
  "webhook",
  "callback",
  "reset-senha",
  "recuperar-senha",
];

export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.includes(slug.toLowerCase().trim());
}
